### ISSUE TITLE
Visual representation of nucleotides?

### ISSUE THREAD

**Issue by anderspitman** [zmertens/SeqAndDestroy#1]
I don't see anything wrong with just using simple sprites of ACGTs, especially starting out, but it would be really awesome if we could somehow make it geometrically valid, where the pieces actually fit together. Probably not for a first draft though. One idea I had was to display the molecules with the letter inside the pyrimidine rings. Thoughts?

**Comment by anderspitman** [comment]
Rough mockup of what I'm talking about:

![purine-3d-balls_edit](https://cloud.githubusercontent.com/assets/7820200/22847585/1d575620-efab-11e6-95c0-f4a8d3039368.png)

**Comment by anderspitman** [comment]
Except that's not adenine lol. But you get the idea.

**Comment by zmertens** [comment]
I think this is something worth focusing on if we can come back to this idea after NoTD. I just want to make sure we have enough for the demo.

**Comment by anderspitman** [comment]
Closing for now.
